on: pull_request
jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR and provide checkout instructions
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR Branch Name
        id: get_pr_branch_name
        run: echo "::set-output name=branch_name::$(echo $GITHUB_REF | cut -d/ -f3)"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello :wave: @{${{ steps.get_pr_opener.outputs.pr_opener }}}, thank you for opening this pull request! To review the changes locally, follow these steps:

            1. Open your terminal.
            2. Run the following command to fetch the pull request changes:
               ```bash
               git fetch origin pull/${{ github.event.pull_request.number }}/head:${{ steps.get_pr_branch_name.outputs.branch_name }}
               ```
            3. Checkout the pull request branch with:
               ```bash
               git checkout ${{ steps.get_pr_branch_name.outputs.branch_name }}
               ```
            4. Now you can review and test the changes locally.
